[package]
name = "opentelemetry-etw-metrics"
version = "0.6.0"
edition = "2021"
description = "OpenTelemetry metrics exporter to ETW (Event Tracing for Windows)"
homepage = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-etw-metrics"
repository = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-etw-metrics"
readme = "README.md"
keywords = ["opentelemetry", "metrics", "etw"]
license = "Apache-2.0"
rust-version = "1.71.1"

[dependencies]
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry_sdk = { workspace = true, features = ["metrics", "rt-tokio"] }
opentelemetry-proto = { workspace = true, features = ["gen-tonic", "metrics"] }
async-trait = "0.1"
prost = "0.13"
tracelogging = "1.2.1"
tracing = { version = "0.1", optional = true }
criterion = { workspace = true, features = ["html_reports", "async_tokio"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }

[features]
internal-logs = ["tracing"]
default = ["internal-logs"]

[package.metadata.cargo-machete]
ignored = ["tracing"]

[[bench]]
name = "exporter"
harness = false
