# Fails to parse due to unknown field 'temporality2'
metrics:
    readers:
        - periodic:
            exporter:
                console:
                    temporality2: delta
resource:
    service.name: "test-service"
    service.version: "1.0.0"
