[package]
name = "geneva-uploader-ffi"
description = "FFI bindings for Geneva uploader"
version = "0.4.0"
edition = "2021"
homepage = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-exporter-geneva/geneva-uploader-ffi"
repository = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-exporter-geneva/geneva-uploader-ffi"
rust-version = "1.85.0"
keywords = ["opentelemetry", "geneva", "ffi", "uploader"]
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
geneva-uploader = { path = "../geneva-uploader", version = "0.4.0" }
opentelemetry-proto = { workspace = true, default-features = false, features = ["logs", "trace", "gen-tonic-messages"] }
tokio = { version = "1.0", features = ["rt-multi-thread"] }
prost = "0.14"

[features]
mock_auth = ["geneva-uploader/mock_auth"]

[lints]
workspace = true

[dev-dependencies]
otlp_builder = { path = "examples/otlp_builder" }
wiremock = "=0.5.22"
base64 = "0.22"
chrono = "0.4"
