[package]
name = "opentelemetry-config-console-example"
version = "0.1.0"
description = "Declarative configuration for OpenTelemetry SDK example using console configuration"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75.0"

[workspace]

[dependencies]
opentelemetry-config-stdout = { path = "../../" }
opentelemetry-config = { path = " ../../../../../opentelemetry-config" }
opentelemetry_sdk = { version = "0.31.0" }
