[package]
name = "opentelemetry-exporter-geneva"
description = "OpenTelemetry exporter for Geneva logs and traces"
version = "0.4.0"
edition = "2021"
homepage = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-exporter-geneva/opentelemetry-exporter-geneva"
repository = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/opentelemetry-exporter-geneva/opentelemetry-exporter-geneva"
rust-version = "1.85.0"
keywords = ["opentelemetry", "geneva", "logs", "traces", "exporter"]
license = "Apache-2.0"

[dependencies]
opentelemetry_sdk = {workspace = true, default-features = false, features = ["logs", "trace"]}
opentelemetry-proto = {workspace = true, default-features = false, features = ["logs", "trace"]}
geneva-uploader = { path = "../geneva-uploader", version = "0.4.0" }
futures = "0.3"

[dev-dependencies]
opentelemetry-appender-tracing = {workspace = true}
opentelemetry = {workspace = true}
opentelemetry_sdk = { workspace = true, features = ["logs", "trace", "experimental_logs_batch_log_processor_with_async_runtime", "experimental_async_runtime", "rt-tokio"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-core = "0.1.31"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["env-filter", "fmt", "registry", "std"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
