# Application specific configurations
version: 1.0.0
service:
  # Telemetry configuration
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              custom:
                custom_string_field: "delta"
                custom_int_field: 42
    resource:
      service.name: "test-service"
      service.version: "1.0.0"
